//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DziennikSzkolny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaNauczycieliPrzedmiotus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaNauczycieliPrzedmiotus()
        {
            this.ListaPrzedmiotowKlasies = new HashSet<ListaPrzedmiotowKlasies>();
            this.ZajetoscSalLekcyjnyches = new HashSet<ZajetoscSalLekcyjnyches>();
        }
    
        public int ID { get; set; }
        public int nauczycielID { get; set; }
        public int przedmiotID { get; set; }
    
        public virtual Nauczyciels Nauczyciels { get; set; }
        public virtual Przedmiots Przedmiots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaPrzedmiotowKlasies> ListaPrzedmiotowKlasies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZajetoscSalLekcyjnyches> ZajetoscSalLekcyjnyches { get; set; }
    }
}
