//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DziennikSzkolny.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klasas> Klasas { get; set; }
        public virtual DbSet<ListaNauczycieliPrzedmiotus> ListaNauczycieliPrzedmiotus { get; set; }
        public virtual DbSet<ListaPrzedmiotowKlasies> ListaPrzedmiotowKlasies { get; set; }
        public virtual DbSet<Nauczyciels> Nauczyciels { get; set; }
        public virtual DbSet<Ocenas> Ocenas { get; set; }
        public virtual DbSet<Ogloszenies> Ogloszenies { get; set; }
        public virtual DbSet<Przedmiots> Przedmiots { get; set; }
        public virtual DbSet<Rodzics> Rodzics { get; set; }
        public virtual DbSet<SaleLekcyjnes> SaleLekcyjnes { get; set; }
        public virtual DbSet<Uczens> Uczens { get; set; }
        public virtual DbSet<ZajetoscSalLekcyjnyches> ZajetoscSalLekcyjnyches { get; set; }
    }
}
