//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DziennikSzkolny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocenas
    {
        public int ocenaID { get; set; }
        public System.DateTime data_wystawienia { get; set; }
        public int uczenID { get; set; }
        public int nauczycielID { get; set; }
        public int przedmiotID { get; set; }
        public double wartosc { get; set; }
        public string opis { get; set; }
    
        public virtual Nauczyciels Nauczyciels { get; set; }
        public virtual Przedmiots Przedmiots { get; set; }
        public virtual Uczens Uczens { get; set; }
    }
}
