//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DziennikSzkolny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLekcyjnes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleLekcyjnes()
        {
            this.ZajetoscSalLekcyjnyches = new HashSet<ZajetoscSalLekcyjnyches>();
        }
    
        public int saleLekcyjneID { get; set; }
        public int numerSali { get; set; }
        public int pietro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZajetoscSalLekcyjnyches> ZajetoscSalLekcyjnyches { get; set; }
    }
}
