//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DziennikSzkolny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZajetoscSalLekcyjnyches
    {
        public int zajetoscSalLekcyjnychID { get; set; }
        public int dzienTygodnia { get; set; }
        public int klasaID { get; set; }
        public int saleLekcyjneID { get; set; }
        public int nauczycielPrzedmiotID { get; set; }
        public int numerGodzinyLekcyjnej { get; set; }
    
        public virtual Klasas Klasas { get; set; }
        public virtual ListaNauczycieliPrzedmiotus ListaNauczycieliPrzedmiotus { get; set; }
        public virtual SaleLekcyjnes SaleLekcyjnes { get; set; }
    }
}
